### ISSUE TITLE
Power off when Keepassxc in system tray

### ISSUE THREAD

**Issue by FMuro** [bugzy/keepassxc-rpm-spec#4]
Hi bugzy, thanks for packaging keepassxc for fedora. I have the following issue. I'm on Fedora 25 workstatio (Gnome). If KeePassXC is in the system tray and I click o the power off button, the system hangs for a while. It later shows the expected message (cancel/restart/power off), but it takes a while. If I cancel all icons from the tray disappear. 

Off topic: have you thought of submitting the package of the official fedora repos? It would be great.

**Comment by bugzy** [comment]
@FMuro 
I thinks the system tray issue should be reported to the main project at https://github.com/keepassxreboot/keepassxc/issues
As to the package on official repos. I am looking into the process of doing that.

**Comment by bugzy** [comment]
As you probably already know there is now an official fedora package at:
https://koji.fedoraproject.org/koji/packageinfo?packageID=24215
