### ISSUE TITLE
keepassxc is in fedora repos.

### ISSUE THREAD

**Issue by sudhirkhanger** [bugzy/keepassxc-rpm-spec#5]
Just a FYI. Looks like KeePassXC is in fedora repos now.

https://bodhi.fedoraproject.org/updates/FEDORA-2017-b6bef5a68d

**Comment by bugzy** [comment]
Thanks. I am aware that it made it into the repos. I am keeping this repo alive mainly for speedy updates, but I may kill it later. Thanks again for the info.
