### ISSUE TITLE
Fedora 28 support

### ISSUE THREAD

**Issue by blfpd** [bugzy/keepassxc-rpm-spec#8]
Could you please add Fedora 28 build? :gift:

**Comment by bugzy** [comment]
Done. See
https://copr.fedorainfracloud.org/coprs/bugzy/keepassxc/build/748769/
or
https://copr.fedorainfracloud.org/coprs/bugzy/keepassxc/

**Comment by blfpd** [comment]
Thanks a lot! :tada: 

Just a heads up, on [the build page](https://copr.fedorainfracloud.org/coprs/bugzy/keepassxc/build/748769/), the version is still `2.3.1-0.fc27`. I don’t know if this is intended.
