### ISSUE TITLE
Unavailable for RHEL?

### ISSUE THREAD

**Issue by quantum77** [bugzy/keepassxc-rpm-spec#9]
# yum install keepassxc
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.dal10.us.leaseweb.net
 * elrepo: syd.mirror.rackspace.com
 * elrepo-extras: syd.mirror.rackspace.com
 * elrepo-kernel: syd.mirror.rackspace.com
 * epel: mirror.mrjester.net
 * extras: mirror.den1.denvercolo.net
 * nux-dextop: mirror.li.nux.ro
 * updates: repo1.sea.innoscale.net
Resolving Dependencies
--> Running transaction check
---> Package keepassxc.x86_64 0:2.2.4-0.el7.centos will be installed
--> Processing Dependency: libQt5X11Extras.so.5(Qt_5)(64bit) for package: keepassxc-2.2.4-0.el7.centos.x86_64
--> Processing Dependency: libgcrypt.so.20(GCRYPT_1.6)(64bit) for package: keepassxc-2.2.4-0.el7.centos.x86_64
--> Processing Dependency: libQt5X11Extras.so.5()(64bit) for package: keepassxc-2.2.4-0.el7.centos.x86_64
--> Processing Dependency: libgcrypt.so.20()(64bit) for package: keepassxc-2.2.4-0.el7.centos.x86_64
--> Running transaction check
---> Package libgcrypt16.x86_64 0:1.6.6-1.el7.centos will be installed
---> Package qt5-qtx11extras.x86_64 0:5.9.2-1.el7 will be installed
--> Processing Dependency: qt5-qtbase(x86-64) = 5.9.2 for package: qt5-qtx11extras-5.9.2-1.el7.x86_64
--> Processing Dependency: libQt5Core.so.5(Qt_5.9)(64bit) for package: qt5-qtx11extras-5.9.2-1.el7.x86_64
--> Running transaction check
---> Package qt5-qtbase.x86_64 0:5.6.2-1.el7 will be updated
--> Processing Dependency: qt5-qtbase = 5.6.2-1.el7 for package: qt5-qtbase-common-5.6.2-1.el7.noarch
--> Processing Dependency: qt5-qtbase(x86-64) = 5.6.2 for package: qt5-qtsensors-5.6.2-1.el7.x86_64
--> Processing Dependency: qt5-qtbase(x86-64) = 5.6.2 for package: qt5-qtwebkit-5.6.2-1.el7.x86_64
--> Processing Dependency: qt5-qtbase(x86-64) = 5.6.2 for package: qt5-qtscript-5.6.2-1.el7.x86_64
--> Processing Dependency: qt5-qtbase(x86-64) = 5.6.2 for package: qt5-qtlocation-5.6.2-1.el7.x86_64
--> Processing Dependency: qt5-qtbase(x86-64) = 5.6.2 for package: qt5-qtxmlpatterns-5.6.2-1.el7.x86_64
--> Processing Dependency: qt5-qtbase(x86-64) = 5.6.2 for package: qt5-qtdeclarative-5.6.2-1.el7.x86_64
--> Processing Dependency: qt5-qtbase(x86-64) = 5.6.2 for package: qt5-qtwebchannel-5.6.2-1.el7.x86_64
--> Processing Dependency: qt5-qtbase(x86-64) = 5.6.2-1.el7 for package: qt5-qtbase-devel-5.6.2-1.el7.x86_64
--> Processing Dependency: qt5-qtbase(x86-64) = 5.6.2 for package: qt5-qtsvg-5.6.2-1.el7.x86_64
--> Processing Dependency: qt5-qtbase(x86-64) = 5.6.2-1.el7 for package: qt5-qtbase-gui-5.6.2-1.el7.x86_64
---> Package qt5-qtbase.x86_64 0:5.9.2-3.el7 will be an update
--> Processing Dependency: libdbus-1.so.3(LIBDBUS_1_3)(64bit) for package: qt5-qtbase-5.9.2-3.el7.x86_64
--> Processing Dependency: libpcre2-16.so.0()(64bit) for package: qt5-qtbase-5.9.2-3.el7.x86_64
--> Running transaction check
---> Package dbus-libs.x86_64 1:1.6.12-17.el7 will be updated
--> Processing Dependency: dbus-libs(x86-64) = 1:1.6.12-17.el7 for package: 1:dbus-1.6.12-17.el7.x86_64
---> Package dbus-libs.x86_64 1:1.10.24-7.el7 will be an update
---> Package pcre2-utf16.x86_64 0:10.23-2.el7 will be installed
---> Package qt5-qtbase.x86_64 0:5.6.2-1.el7 will be updated
--> Processing Dependency: qt5-qtbase(x86-64) = 5.6.2 for package: qt5-qtwebkit-5.6.2-1.el7.x86_64
---> Package qt5-qtbase-common.noarch 0:5.6.2-1.el7 will be updated
---> Package qt5-qtbase-common.noarch 0:5.9.2-3.el7 will be an update
---> Package qt5-qtbase-devel.x86_64 0:5.6.2-1.el7 will be updated
---> Package qt5-qtbase-devel.x86_64 0:5.9.2-3.el7 will be an update
---> Package qt5-qtbase-gui.x86_64 0:5.6.2-1.el7 will be updated
---> Package qt5-qtbase-gui.x86_64 0:5.9.2-3.el7 will be an update
---> Package qt5-qtdeclarative.x86_64 0:5.6.2-1.el7 will be updated
--> Processing Dependency: qt5-qtdeclarative(x86-64) = 5.6.2 for package: qt5-qtwebkit-5.6.2-1.el7.x86_64
---> Package qt5-qtdeclarative.x86_64 0:5.9.2-1.el7 will be an update
---> Package qt5-qtlocation.x86_64 0:5.6.2-1.el7 will be updated
---> Package qt5-qtlocation.x86_64 0:5.9.2-1.el7 will be an update
---> Package qt5-qtscript.x86_64 0:5.6.2-1.el7 will be updated
---> Package qt5-qtscript.x86_64 0:5.9.2-1.el7 will be an update
---> Package qt5-qtsensors.x86_64 0:5.6.2-1.el7 will be updated
---> Package qt5-qtsensors.x86_64 0:5.9.2-1.el7 will be an update
---> Package qt5-qtsvg.x86_64 0:5.6.2-1.el7 will be updated
---> Package qt5-qtsvg.x86_64 0:5.9.2-1.el7 will be an update
---> Package qt5-qtwebchannel.x86_64 0:5.6.2-1.el7 will be updated
---> Package qt5-qtwebchannel.x86_64 0:5.9.2-1.el7 will be an update
---> Package qt5-qtxmlpatterns.x86_64 0:5.6.2-1.el7 will be updated
---> Package qt5-qtxmlpatterns.x86_64 0:5.9.2-1.el7 will be an update
--> Running transaction check
---> Package dbus.x86_64 1:1.6.12-17.el7 will be updated
--> Processing Dependency: dbus = 1:1.6.12-17.el7 for package: 1:dbus-devel-1.6.12-17.el7.x86_64
--> Processing Dependency: dbus = 1:1.6.12-17.el7 for package: 1:dbus-x11-1.6.12-17.el7.x86_64
---> Package dbus.x86_64 1:1.10.24-7.el7 will be an update
---> Package qt5-qtbase.x86_64 0:5.6.2-1.el7 will be updated
--> Processing Dependency: qt5-qtbase(x86-64) = 5.6.2 for package: qt5-qtwebkit-5.6.2-1.el7.x86_64
---> Package qt5-qtdeclarative.x86_64 0:5.6.2-1.el7 will be updated
--> Processing Dependency: qt5-qtdeclarative(x86-64) = 5.6.2 for package: qt5-qtwebkit-5.6.2-1.el7.x86_64
--> Running transaction check
---> Package dbus-devel.x86_64 1:1.6.12-17.el7 will be updated
---> Package dbus-devel.x86_64 1:1.10.24-7.el7 will be an update
---> Package dbus-x11.x86_64 1:1.6.12-17.el7 will be updated
---> Package dbus-x11.x86_64 1:1.10.24-7.el7 will be an update
---> Package qt5-qtbase.x86_64 0:5.6.2-1.el7 will be updated
--> Processing Dependency: qt5-qtbase(x86-64) = 5.6.2 for package: qt5-qtwebkit-5.6.2-1.el7.x86_64
---> Package qt5-qtdeclarative.x86_64 0:5.6.2-1.el7 will be updated
--> Processing Dependency: qt5-qtdeclarative(x86-64) = 5.6.2 for package: qt5-qtwebkit-5.6.2-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: qt5-qtwebkit-5.6.2-1.el7.x86_64 (@epel)
           Requires: qt5-qtdeclarative(x86-64) = 5.6.2
           Removing: qt5-qtdeclarative-5.6.2-1.el7.x86_64 (@base)
               qt5-qtdeclarative(x86-64) = 5.6.2-1.el7
           Updated By: qt5-qtdeclarative-5.9.2-1.el7.x86_64 (base)
               qt5-qtdeclarative(x86-64) = 5.9.2-1.el7
Error: Package: qt5-qtwebkit-5.6.2-1.el7.x86_64 (@epel)
           Requires: qt5-qtbase(x86-64) = 5.6.2
           Removing: qt5-qtbase-5.6.2-1.el7.x86_64 (@base)
               qt5-qtbase(x86-64) = 5.6.2-1.el7
           Updated By: qt5-qtbase-5.9.2-3.el7.x86_64 (base)
               qt5-qtbase(x86-64) = 5.9.2-3.el7
 You could try using --skip-broken to work around the problem
** Found 37 pre-existing rpmdb problem(s), 'yum check' output follows:
acpid-2.0.19-8.el7.x86_64 has missing requires of /sbin/chkconfig
akonadi-mysql-1.9.2-4.el7.x86_64 has missing requires of /usr/sbin/update-alternatives
binutils-2.25.1-32.base.el7_4.2.x86_64 has missing requires of /usr/sbin/alternatives
chromium-libs-61.0.3163.100-1.el7.x86_64 has missing requires of /usr/sbin/update-alternatives
chromium-libs-media-61.0.3163.100-1.el7.x86_64 has missing requires of /usr/sbin/update-alternatives
cifs-utils-6.2-10.el7.x86_64 has missing requires of /usr/sbin/alternatives
1:cups-client-1.6.3-29.el7.x86_64 has missing requires of /usr/sbin/alternatives
dbus-glib-0.100-7.el7.x86_64 has missing requires of chkconfig >= ('0', '1.3.26', None)
fuse-2.9.2-8.el7.x86_64 has missing requires of chkconfig
genisoimage-1.1.11-23.el7.x86_64 has missing requires of /usr/sbin/alternatives
icedtea-web-1.6.2-4.el7.x86_64 has missing requires of /usr/sbin/alternatives
icedtea-web-1.6.2-4.el7.x86_64 has missing requires of chkconfig >= ('0', '1.7', None)
imsettings-1.6.3-9.el7.x86_64 has missing requires of /usr/sbin/alternatives
initscripts-9.49.39-1.el7_4.1.x86_64 has missing requires of /sbin/chkconfig
iputils-20160308-10.el7.x86_64 has missing requires of /sbin/chkconfig
1:java-1.7.0-openjdk-headless-1.7.0.171-2.6.13.0.el7_4.x86_64 has missing requires of /usr/sbin/alternatives
1:java-1.7.0-openjdk-headless-1.7.0.171-2.6.13.0.el7_4.x86_64 has missing requires of chkconfig >= ('0', '1.7', None)
1:java-1.8.0-openjdk-headless-1.8.0.161-0.b14.el7_4.x86_64 has missing requires of /usr/sbin/alternatives
1:java-1.8.0-openjdk-headless-1.8.0.161-0.b14.el7_4.x86_64 has missing requires of chkconfig >= ('0', '1.7', None)
1:mariadb-5.5.56-2.el7.x86_64 has missing requires of /usr/sbin/update-alternatives
1:mariadb-server-5.5.56-2.el7.x86_64 has missing requires of /usr/sbin/update-alternatives
nss-3.28.4-15.el7_4.x86_64 has missing requires of /usr/sbin/update-alternatives
p11-kit-trust-0.23.5-3.el7.x86_64 has missing requires of /usr/sbin/update-alternatives
2:postfix-2.10.1-6.el7.x86_64 has missing requires of /usr/sbin/alternatives
samba-client-4.6.2-12.el7_4.x86_64 has missing requires of /usr/sbin/update-alternatives
1:smartmontools-6.2-8.el7.x86_64 has missing requires of chkconfig
sssd-client-1.15.2-50.el7_4.11.x86_64 has missing requires of /usr/sbin/alternatives
sssd-common-1.15.2-50.el7_4.11.x86_64 has missing requires of chkconfig
sssd-common-1.15.2-50.el7_4.11.x86_64 has missing requires of chkconfig
star-1.5.2-13.el7.x86_64 has missing requires of /usr/sbin/alternatives
tigervnc-server-minimal-1.8.0-2.el7_4.x86_64 has missing requires of chkconfig
unrar-5.0.12-2.el7.nux.x86_64 has missing requires of chkconfig
whois-5.1.1-2.el7.x86_64 has missing requires of /usr/sbin/update-alternatives
wine-core-3.0-1.el7.x86_64 has missing requires of /usr/sbin/alternatives
wine-core-3.0-1.el7.x86_64 has missing requires of /usr/sbin/alternatives
wine-desktop-3.0-1.el7.noarch has missing requires of /sbin/chkconfig
wodim-1.1.11-23.el7.x86_64 has missing requires of /usr/sbin/alternatives

**Comment by bugzy** [comment]
@quantum77 
you will need to add the repo at https://copr.fedorainfracloud.org/coprs/bugzy/keepassxc/repo/epel-7/bugzy-keepassxc-epel-7.repo before you can install keepassxc

**Comment by bugzy** [comment]
More info here: https://copr.fedorainfracloud.org/coprs/bugzy/keepassxc/
